web/webgui/api/urls.py
from django.urls import path
from . import views
from rest_framework.authtoken import views as auth_views

app_name = "api"

urlpatterns = [
    path(
        "retrieve/<int:run_id>/",
        views.ConfigurationsForRunView.as_view(),
        name="conf_for_run",
    ),
    path(
        "retrieve/release/<slug:release_name>/",
        views.ConfigurationsForReleaseView.as_view(),
        name="conf_for_release",
    ),
    path(
        "retrieve/<int:min_run_id>/<int:max_run_id>/",
        views.ConfigurationsForRunMinMaxView.as_view(),
        name="conf_for_run_min_max",
    ),
    path(
        "retrieve/<str:name>/<int:run_id>/",
        views.ConfigurationRetrieveView.as_view(),
        name="params_for_class",
    ),
    path(
        "retrieve/validity/latest/<int:run_id>/",
        views.LatestConfigurationValidityDatesForRunView.as_view(),
        name="latest_validity_for_run",
    ),
    path(
        "retrieve/validity/latest/<int:min_run_id>/<int:max_run_id>",
        views.LatestConfigurationValidityDatesForRunMinMaxView.as_view(),
        name="latest_validity_for_run_min_max",
    ),
    path("runs/", views.FilesCreateView.as_view(), name="runs_create"),
    path("api-token-auth/", auth_views.obtain_auth_token, name="token_for_user"),
]

web/webgui/interact/urls.py
from django.urls import path, re_path
from . import views
from django.urls import reverse_lazy

from django.views.generic.base import RedirectView

app_name = "interact"

urlpatterns = [
    path("main/", views.main, name="main"),
    path("add/", views.ParseView.as_view(), name="parse"),
    path("retrieve/", views.ExtractView.as_view(), name="extract"),
    path("download/", views.download, name="download"),
    path("release/", views.ReleaseView.as_view(), name="release"),
    path("login/", views.InteractLoginView.as_view(), name="login"),
    path("logout/", views.InteractLogoutView.as_view(), name="logout"),
    path("files/", views.FilesListView.as_view(), name="files"),
    re_path(r"^.*$", RedirectView.as_view(url=reverse_lazy("interact:main"))),
]

web/webgui/webgui/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    re_path(
        r"^swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    re_path(
        r"^swagger/$",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    re_path(
        r"^redoc/$", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"
    ),
    path("admin/", admin.site.urls),
    path("interact/", include("interact.urls", namespace="interact")),
    path("api/", include("api.urls", namespace="api")),
]

web/webgui/interact/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token


@receiver(post_save, sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender, instance=None, created=False, **kwargs):
    if created:
        Token.objects.create(user=instance)

web/webgui/interact/forms/download.py
from django import forms
from django.core.exceptions import ValidationError
import datetime


class DownloadForm(forms.Form):

    valid_from = forms.DateTimeField(
        required=True, widget=forms.widgets.HiddenInput(attrs={"type": "hidden"})
    )
    valid_to = forms.DateTimeField(
        required=True, widget=forms.widgets.HiddenInput(attrs={"type": "hidden"})
    )
    version = forms.IntegerField(
        required=True, widget=forms.widgets.HiddenInput(attrs={"type": "hidden"})
    )

web/webgui/interact/forms/login.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms


class LoginForm(AuthenticationForm):
    class Meta:
        widgets = {
            "username": forms.widgets.TextInput(
                attrs={
                    "type": "text",
                    "class": "form-control",
                    "aria-describedby": "username-help",
                }
            ),
            "password": forms.widgets.PasswordInput(
                attrs={
                    "type": "password",
                    "class": "form-control",
                    "aria-describedby": "password-help",
                }
            ),
        }

    username = forms.CharField(widget=Meta.widgets["username"])
    password = forms.CharField(widget=Meta.widgets["password"])

web/webgui/interact/forms/release.py
from django import forms
from core.models import Release
from django.core.exceptions import ValidationError
import datetime


class ReleaseForm(forms.ModelForm):
    class Meta:
        model = Release
        fields = ["name", "comment"]
        widgets = {
            "comment": forms.widgets.Textarea(
                attrs={
                    "type": "textarea",
                    "class": "form-control",
                    "aria-describedby": "comment-help",
                    "rows": 3,
                }
            ),
            "name": forms.widgets.TextInput(
                attrs={
                    "type": "text",
                    "class": "form-control",
                    "aria-describedby": "name-help",
                }
            ),
        }
        labels = {"name": "name", "comment": "comment"}
        help_texts = {
            "name": "The name of a release.",
            "comment": "The optional comment about a release.",
        }
        error_messages = {
            "name": {
                "invalid": "Enter a valid name consisting of letters, numbers, underscores or hyphens."
            }
        }

    def clean_name(self):
        cleaned_data = super(ReleaseForm, self).clean()
        model = self.Meta.model
        name = cleaned_data["name"]
        releases = model.objects.filter(name=name)
        if releases:
            raise ValidationError(
                "There is already a release with such a name in the database."
            )
        return name

web/webgui/interact/views.py
from django.shortcuts import render, redirect
from .forms import ExtractForm, DownloadForm, ParseForm, ReleaseForm, LoginForm
from core.models import Release, Files
from django.apps import apps
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, Http404
from django.views import View
from django.urls import reverse_lazy
from .scripts.extractor import (
    Extractor,
    DateTimes,
    Run,
    FileName,
    SearchDetails,
    VersionDetails,
)
from .scripts.parser import (
    handle_uploaded_file,
    ValidityDates,
    Runs,
    Filenames,
    write_to_database,
)
from django.http import FileResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger, Page
from typing import Optional, Tuple, List
from django.db.models.query import QuerySet

extractor = Extractor()


class InteractLoginRequiredMixin(LoginRequiredMixin):
    login_url = reverse_lazy("interact:login")


class InteractLoginView(LoginView):
    template_name = "interact/login.html"
    redirect_authenticated_user = True
    authentication_form = LoginForm


class InteractLogoutView(InteractLoginRequiredMixin, LogoutView):
    next_page = reverse_lazy("interact:login")


class PaginatedMixin:
    pages_per_pagination = 3
    records_per_page = 3

    def get_paginator(
        self, queryset: QuerySet, page: Optional[int]
    ) -> Tuple[Page, List]:
        paginator = Paginator(queryset, self.records_per_page)
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page = 1
            page_obj = paginator.page(page)
        except EmptyPage:
            page = paginator.num_pages
            page_obj = paginator.page(page)
        page = int(page)
        page_range = paginator.page_range[
            page - 1 : page + self.pages_per_pagination - 1
        ]
        if len(page_range) < self.pages_per_pagination:
            page_range = paginator.page_range[-self.pages_per_pagination :]
        return page_obj, page_range


@login_required(login_url=reverse_lazy("interact:login"))
@require_http_methods(["GET"])
def main(request):
    return render(request, "interact/base.html")


class ReleaseView(PaginatedMixin, InteractLoginRequiredMixin, View):
    release_form_class = ReleaseForm
    template_name = "interact/release.html"
    records_per_page = 10

    def get(self, request, *args, **kwargs):
        page = request.GET.get("page")
        releases, page_range = self.get_paginator(Release.objects.all(), page)
        release_form = self.release_form_class()
        return render(
            request,
            self.template_name,
            {
                "release_form": release_form,
                "page_obj": releases,
                "page_range": page_range,
            },
        )

    def post(self, request, *args, **kwargs):
        release_form = self.release_form_class(request.POST)
        saved = False
        if release_form.is_valid():
            release_form.save()
            saved = True
        releases, page_range = self.get_paginator(Release.objects.all(), 1)
        return render(
            request,
            self.template_name,
            {
                "release_form": release_form,
                "saved": saved,
                "page_obj": releases,
                "page_range": page_range,
            },
        )


class FilesListView(PaginatedMixin, InteractLoginRequiredMixin, View):
    template_name = "interact/files.html"
    records_per_page = 10

    def get(self, request, *args, **kwargs):
        page = request.GET.get("page")
        releases, page_range = self.get_paginator(Files.objects.all(), page)
        return render(
            request,
            self.template_name,
            {"page_obj": releases, "page_range": page_range},
        )


class ParseView(InteractLoginRequiredMixin, View):
    parse_form_class = ParseForm
    template_name = "interact/parse.html"

    def get(self, request, *args, **kwargs):
        parse_form = self.parse_form_class()
        return render(request, self.template_name, {"parse_form": parse_form})

    def post(self, request, *args, **kwargs):
        parse_form = self.parse_form_class(request.POST, request.FILES)

        sent = False
        if parse_form.is_valid():
            cd = parse_form.cleaned_data
            conf_file = handle_uploaded_file(cd["configuration"])
            release = Release.objects.filter(name=cd["release"])
            if not release:
                return render(
                    request,
                    self.template_name,
                    {
                        "parse_form": parse_form,
                        "error": ("The provided release does not exist.",),
                    },
                )
            release = release.first()
            valid_from = cd.get("valid_from")
            valid_to = cd.get("valid_to")
            if not valid_from and not valid_to:
                vd = ValidityDates()

                run_from = cd.get("run_from")
                run_to = cd.get("run_to")
                filename_from = cd.get("filename_from")
                filename_to = cd.get("filename_to")
                arg = None

                if run_from and run_to:
                    arg = Runs(run_from, run_to)
                elif filename_from and filename_to:
                    arg = Filenames(filename_from, filename_to)

                if arg:
                    try:
                        valid_from, valid_to = vd.from_params(arg)
                    except Exception:
                        error = (
                            "Unable to extract validity dates from given parameters.",
                        )
                        return render(
                            request,
                            self.template_name,
                            {"parse_form": parse_form, "error": error},
                        )

            if valid_from and valid_to:
                try:
                    write_to_database(
                        conf_file_path=conf_file,
                        release=release,
                        version=cd.get("version"),
                        valid_from=valid_from,
                        valid_to=valid_to,
                        remarks=cd.get("remarks"),
                    )
                    sent = True

                except Exception:
                    error = (
                        """
                             Unable to write to the database. 
                             Check if all the constraints meet the requirements.""",
                    )
                    return render(
                        request,
                        self.template_name,
                        {"parse_form": parse_form, "error": error},
                    )

            else:
                return render(
                    request,
                    self.template_name,
                    {
                        "parse_form": parse_form,
                        "error": ("Failed to extract some of the validity dates.",),
                    },
                )

        return render(
            request, self.template_name, {"parse_form": parse_form, "sent": sent}
        )


@login_required(login_url=reverse_lazy("interact:login"))
@require_http_methods(["POST"])
def download(request):
    form = DownloadForm(request.POST)
    if form.is_valid():
        details = SearchDetails(
            form.cleaned_data["valid_from"],
            form.cleaned_data["valid_to"],
            form.cleaned_data["version"],
        )
        filename = extractor.write_to_file(details)
        return FileResponse(open(filename, "rb"), as_attachment=True)
    raise Http404("validity dates or version are not valid")


class ExtractView(InteractLoginRequiredMixin, View):
    login_url = reverse_lazy("interact:login")
    extract_form_class = ExtractForm
    download_form_class = DownloadForm
    template_name = "interact/extract.html"

    def get(self, request, *args, **kwargs):
        extract_form = self.extract_form_class()
        return render(request, self.template_name, {"extract_form": extract_form})

    def post(self, request, *args, **kwargs):
        extract_form = self.extract_form_class(request.POST)
        download_form = self.download_form_class()

        versions_table = None
        version_exists = True

        if extract_form.is_valid():
            cd = extract_form.cleaned_data
            valid_from = cd.get("valid_from")
            valid_to = cd.get("valid_to")
            version = cd.get("version")
            filename = cd.get("filename")
            run = cd.get("run")

            if valid_from and valid_to:
                param = DateTimes((valid_from, valid_to))
            elif run:
                param = Run(run)
            elif filename:
                param = FileName(filename)

            available_versions = extractor.process(param)
            if version:
                version_exists = extractor.version_exists(available_versions, version)
                if version_exists:
                    versions_table = extractor.filter_by_version(
                        available_versions, version
                    )
            if not version or not version_exists:
                version_exists = False
                versions_table = available_versions

            versions_table = extractor.convert_datetimes(versions_table)

        return render(
            request,
            self.template_name,
            {
                "extract_form": extract_form,

web/webgui/interact/templates/interact/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> {% block title %} {% endblock %} </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
        {% block styles %} {% include "interact/includes/styles.html" %} {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light" id="navigation">
            <a class="navbar-brand">Interact</a> 
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "interact:main" %}">Main</a>
                </li>
                <li class="nav-item>">
                    <a class="nav-link" href="{% url "interact:parse" %}">Add</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "interact:extract" %}">Retrieve</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "interact:release" %}">Release</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url "interact:files" %}">Runs</a>
                </li>
                {% if user.is_superuser %}
                    <li class="nav-item">
                        <a class="nav-link" id="admin-link" href="{% url 'admin:index' %}">Admin</a>
                    </li>
                {% endif %}
            </ul>
            <div class="container d-flex flex-row-reverse">
                {% if user.is_authenticated%}
                    <div class="row">
                        <p class="col d-flex flex-row-reverse" id="login-user">
                                Logged in as: {{ user.username }}
                        </p>
                        <form method="POST" action="{% url "interact:logout" %}">
                            {% csrf_token %}
                            <button class="btn btn-outline-danger" type="submit"> Log out</button>
                        </form>
                    </div>
                {% else %}
                    <a href="{% url "interact:login" %}"> 
                        <button class="btn btn-outline-success" type="submit"> Log in</button>
                    </a>
                {% endif %}
            </div>

        </nav>

        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    {% block scripts %} {% include "interact/includes/scripts.html" %} {% endblock %}
    </body>
</html>

web/webgui/interact/templates/interact/extract.html
{% extends "interact/base.html" %}

{% block title %} Retrieve the configurations {% endblock %}

{% block content %}
    <div class="header-form">
        <h1> Retrieve the configurations from the database. </h1>
    </div>

    {% if versions.empty %}
        <div class="alert alert-warning" role="alert">
            <p>
                There are no configurations matched to the provided parameters.
            </p>
        </div>
    {% elif version_exists is False %}
        <div class="alert alert-warning" role="alert">
            <p>
                You have not provided a version or the provided version does not exist.
            </p>
        </div>
    {% endif %}

    {% include "interact/includes/forms/extract_form.html" with form=extract_form %}
    
    {% if versions is not None and not versions.empty %}
        <div>
            <table class="table">
                <thead>
                    <tr>
                        {% for col in versions.columns %}
                            <th scope="col"> {{ col }} </th>
                        {% endfor %}
                        <th> Download </th>
                    <tr>
                </thead>
                <tbody>
                    {% for index, row in versions.iterrows %}
                        <tr>
                        {% for item in row %}
                            <td> {{ item }} </td>
                        {% endfor %}
                            <td>
                                <form action={% url "interact:download" %} method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="valid_from" value="{{row.0}}">
                                    <input type="hidden" name="valid_to" value="{{row.1}}">
                                    <input type="hidden" name="version" value="{{row.2}}">
                                    <button type="submit" class="btn btn-success btn-sm">
                                        <span class="oi oi-data-transfer-download"></span>
                                    </button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>

    {% endif %}

{% endblock %}

web/webgui/interact/templates/interact/files.html
{% extends "interact/base.html" %}

{% block title %} Runs List {% endblock %}

{% block content %}
    <div class="header-form">
        <h1> Runs List </h1>
    </div>
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th> run start time </th>
                    <th> run stop time </th>
                    <th> run id </th>
                    <th> file name </th>
                    <th> remarks </th>
                </tr>
            </thead>
            <tbody>
                {% for file in page_obj %}
                    <tr>
                        <td> {{ file.start_time }} </td>
                        <td> {{ file.stop_time  }} </td>
                        <td> {{ file.run_id }} </td>
                        <td> {{ file.file_name|truncatewords:30 }} </td>
                        <td> {{ file.remarks|truncatewords:30|linebreaks }} </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include "interact/includes/pagination.html" with page=page_obj %}

{% endblock %}

web/webgui/interact/templates/interact/login.html
{% extends "interact/base.html" %}
{% load static %}

{% block title %} Log in {% endblock %}

{% block content %}
<div class="centered" id="log-in">
    <div class="col">
        <img src="{% static "images/logo_SiFi_CC__negatyw_small.jpg" %}" alt="Si-Fi CC">
    </div>
    <h1> Log in </h1>
    {% include "interact/includes/forms/login_form.html" with form=form site=site next=next site=site site_name=site_name %}
</div>

{% endblock %}

web/webgui/interact/templates/interact/parse.html
{% extends "interact/base.html"%}

{% block title %} Add a Configuration {% endblock %}

{% block content %}

    <div class="header-form">
        <h1> Add a configuration to the database. </h1>
    </div>

    {% if sent is True %}
        <div class="alert alert-success" role="alert">
            The configuration has been added to the database.
        </div>
    {% endif %}

    {% include "interact/includes/forms/parse_form.html" with form=parse_form %}

{% endblock %}

web/webgui/interact/templates/interact/release.html
{% extends "interact/base.html"%}

{% block title %} Add a Release {% endblock %}

{% block content %}

    <div class="header-form">
        <h1> Add a release to the database. </h1>
    </div>

    {% if saved is True %}
        <div class="alert alert-success" role="alert">
            The release has been successfully saved.
        </div>
    {% endif %}
    
    {% include "interact/includes/forms/release_form.html" with form=release_form %}

    <div class="header-form">
        <h3> Releases </h3>
    </div>

    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th> name </th>
                    <th> comment </th>
                </tr>
            </thead>
            <tbody>
                {% for release in page_obj %}
                    <tr>
                        <td> {{ release.name|truncatewords:30 }} </td>
                        <td> {{ release.comment|truncatewords:30|linebreaks }} </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% include "interact/includes/pagination.html" with page=page_obj %}

{% endblock %}